[project]
name = "python3-lgpd-crawler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "blinker==1.9.0",
    "certifi==2025.11.12",
    "cffi==2.0.0 ; platform_python_implementation != 'PyPy'",
    "charset-normalizer==3.4.4",
    "click==8.3.1",
    "colorama==0.4.6 ; sys_platform == 'win32'",
    "cryptography==46.0.3",
    "flask==3.1.2",
    "flask-sqlalchemy==3.1.1",
    "greenlet==3.3.0 ; platform_machine == 'AMD64' or platform_machine == 'WIN32' or platform_machine == 'aarch64' or platform_machine == 'amd64' or platform_machine == 'ppc64le' or platform_machine == 'win32' or platform_machine == 'x86_64'",
    "idna==3.11",
    "itsdangerous==2.2.0",
    "jinja2==3.1.6",
    "mariadb==1.1.14",
    "markupsafe==3.0.3",
    "mysql==0.0.3",
    "mysqlclient==2.2.7",
    "oracledb==3.4.1",
    "packaging==25.0",
    "pillow==12.0.0",
    "psycopg2-binary==2.9.11",
    "pycparser==2.23 ; implementation_name != 'PyPy' and platform_python_implementation != 'PyPy'",
    "reportlab==4.4.7",
    "requests==2.32.5",
    "setuptools==80.9.0",
    "sqlalchemy==2.0.45",
    "typing-extensions==4.15.0",
    "urllib3==2.6.2",
    "werkzeug==3.1.4",
]
